packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@openapitools/openapi-generator-cli': true
  '@reown/appkit': false
  bufferutil: false
  core-js-pure: true
  esbuild: true
  keccak: false
  utf-8-validate: false
  workerd: true

minimumReleaseAgeExclude:
  - knip@6.33.0
  - '@privy-io/api-base@1.11.0'
  - '@privy-io/are-addresses-equal@0.0.13'
  - '@privy-io/chains@0.6.1'
  - '@privy-io/encoding@0.2.3'
  - '@privy-io/ethereum@0.2.4'
  - '@privy-io/js-sdk-core@0.76.1'
  - '@privy-io/popup@0.0.6'
  - '@privy-io/react-auth@3.44.0'
  - '@privy-io/routes@0.4.1'
  - '@privy-io/std@0.0.1'
